### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [jakevossen5/Apollo-Trivia#28]
Hi,

Since this app is GNU GPL v3 licensed, are you ok with the inclusion of this app in [F-Droid](https://f-droid.org/)? There is a strong community behind.

There are already a [Request For Packaging](https://gitlab.com/fdroid/rfp/issues/341) and a [Merge Request](https://gitlab.com/fdroid/fdroiddata/merge_requests/3160)...

**Comment by Poussinou** [comment]
Perfect 👍

**Comment by doublah** [comment]
Is now in repo, issue can be closed.
